Add Permit Launch Week
supabase-community/launchweek.dev pull request #41
Opened 2024-10-16 08:26 UTC by gemanor

## What kind of change does this PR introduce?

Add Permit Launch Week

## What is the current behavior?

Missing link

## What is the new behavior?

Added link

## Additional context

2024-10-16 12:15 UTC, fmerian requested changes
thanks for the suggestion, @gemanor! they are duplicate links tho. I'd keep the `Go to launch page` only.

2024-10-18 09:53 UTC, gemanor commented on README.md
> +- 2024 / 10 / 28-01: Permit Launch Week. [Teaser ↗︎](https://launchweek.permit.io) [Go to launch page ↗︎](https://launchweek.permit.io)
```suggestion
- 2024 / 10 / 28-01: Permit Launch Week [Teaser ↗︎](https://x.com/permit_io/status/1847213978352545944) (https://launchweek.permit.io) [Go to launch page ↗︎](https://launchweek.permit.io)
```

2024-10-18 09:54 UTC, gemanor commented on README.md
> +- 2024 / 10 / 28-01: Permit Launch Week. [Teaser ↗︎](https://launchweek.permit.io) [Go to launch page ↗︎](https://launchweek.permit.io)
```suggestion
- 2024 / 10 / 28-01: Permit Launch Week. [Teaser ↗︎](https://x.com/permit_io/status/1847213978352545944) [Go to launch page ↗︎](https://launchweek.permit.io)
```

2024-10-18 09:54 UTC, gemanor commented
Thanks for the review @fmerian, just fixed it.

2024-10-18 16:29 UTC, fmerian approved these changes
LGTM :)

2024-10-18 16:29 UTC, merged